In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\Aldhair\Desktop\hr-analytics-attrition\data\raw\WA_Fn-UseC_-HR-Employee-Attrition.csv', sep = ',')

print (f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")
df.head()

Filas: 1470, Columnas: 35

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
#Verificamos columnas con un valor único
for col in df.columns:
    if df[col].nunique() == 1:
        print(f"{col}: valor único = {df[col].unique()}")

EmployeeCount: valor único = [1]
Over18: valor único = <StringArray>
['Y']
Length: 1, dtype: str
StandardHours: valor único = [80]

In [ ]:
columnas_a_eliminar = ['EmployeeCount', 'Over18', 'StandardHours', 'EmployeeNumber']

df = df.drop(columns=columnas_a_eliminar)

print (f"Columnas restantes: {df.shape[1]}")
df.columns.tolist()

Columnas restantes: 31

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [7]:
columnas_texto = df.select_dtypes(include='object').columns.tolist()
print(columnas_texto)

for col in columnas_texto:
    print(f"\n{col}: {df[col].unique()}")

['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

Attrition: <StringArray>
['Yes', 'No']
Length: 2, dtype: str

BusinessTravel: <StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
Length: 3, dtype: str

Department: <StringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str

EducationField: <StringArray>
[   'Life Sciences',            'Other',          'Medical',
        'Marketing', 'Technical Degree',  'Human Resources']
Length: 6, dtype: str

Gender: <StringArray>
['Female', 'Male']
Length: 2, dtype: str

JobRole: <StringArray>
[          'Sales Executive',        'Research Scientist',
     'Laboratory Technician',    'Manufacturing Director',
 'Healthcare Representative',                   'Manager',
      'Sales Representative',         'Research Director',
           'Human Resources']
Length: 9, dtype: str

MaritalStatus: <StringArray>
['Single', 'Married', 'Divorced']
Length: 3, dtype: str

OverTime: <StringArray>
['Yes', 'No']
Length: 2, dtype: str

C:\Users\Aldhair\AppData\Local\Temp\ipykernel_6352\1608170838.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df.select_dtypes(include='object').columns.tolist()

In [8]:
# Convertimos Yes/No y Female/Male a 0/1
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

df[['Attrition', 'OverTime', 'Gender']].head()

   Attrition  OverTime  Gender
0          1         1       0
1          0         0       1
2          1         1       1
3          0         1       0
4          0         0       1

In [9]:
columnas_multiples = ['BusinessTravel', 'Department', 'EducationField', 'JobRole', 'MaritalStatus']

df = pd.get_dummies(df, columns=columnas_multiples, drop_first=True)

print (f"Columnas ahora: {df.shape[1]}")
df.head()

Columnas ahora: 45

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single
0,41,1,1102,1,2,2,0,94,3,2,...,False,False,False,False,False,False,True,False,False,True
1,49,0,279,8,1,3,1,61,2,2,...,False,False,False,False,False,True,False,False,True,False
2,37,1,1373,2,2,4,1,92,2,1,...,False,True,False,False,False,False,False,False,False,True
3,33,0,1392,3,4,4,0,56,3,1,...,False,False,False,False,False,True,False,False,True,False
4,27,0,591,2,1,1,1,40,3,1,...,False,True,False,False,False,False,False,False,True,False

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 45 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   Attrition                          1470 non-null   int64
 2   DailyRate                          1470 non-null   int64
 3   DistanceFromHome                   1470 non-null   int64
 4   Education                          1470 non-null   int64
 5   EnvironmentSatisfaction            1470 non-null   int64
 6   Gender                             1470 non-null   int64
 7   HourlyRate                         1470 non-null   int64
 8   JobInvolvement                     1470 non-null   int64
 9   JobLevel                           1470 non-null   int64
 10  JobSatisfaction                    1470 non-null   int64
 11  MonthlyIncome                      1470 non-null   int64
 12  MonthlyRate                        1470 non-null   int64
 13  NumCompaniesWorked                 1470 non-null   int64
 14  OverTime                           1470 non-null   int64
 15  PercentSalaryHike                  1470 non-null   int64
 16  PerformanceRating                  1470 non-null   int64
 17  RelationshipSatisfaction           1470 non-null   int64
 18  StockOptionLevel                   1470 non-null   int64
 19  TotalWorkingYears                  1470 non-null   int64
 20  TrainingTimesLastYear              1470 non-null   int64
 21  WorkLifeBalance                    1470 non-null   int64
 22  YearsAtCompany                     1470 non-null   int64
 23  YearsInCurrentRole                 1470 non-null   int64
 24  YearsSinceLastPromotion            1470 non-null   int64
 25  YearsWithCurrManager               1470 non-null   int64
 26  BusinessTravel_Travel_Frequently   1470 non-null   bool
 27  BusinessTravel_Travel_Rarely       1470 non-null   bool
 28  Department_Research & Development  1470 non-null   bool
 29  Department_Sales                   1470 non-null   bool
 30  EducationField_Life Sciences       1470 non-null   bool
 31  EducationField_Marketing           1470 non-null   bool
 32  EducationField_Medical             1470 non-null   bool
 33  EducationField_Other               1470 non-null   bool
 34  EducationField_Technical Degree    1470 non-null   bool
 35  JobRole_Human Resources            1470 non-null   bool
 36  JobRole_Laboratory Technician      1470 non-null   bool
 37  JobRole_Manager                    1470 non-null   bool
 38  JobRole_Manufacturing Director     1470 non-null   bool
 39  JobRole_Research Director          1470 non-null   bool
 40  JobRole_Research Scientist         1470 non-null   bool
 41  JobRole_Sales Executive            1470 non-null   bool
 42  JobRole_Sales Representative       1470 non-null   bool
 43  MaritalStatus_Married              1470 non-null   bool
 44  MaritalStatus_Single               1470 non-null   bool
dtypes: bool(19), int64(26)
memory usage: 326.0 KB

In [11]:
df.to_csv(r'C:\Users\Aldhair\Desktop\hr-analytics-attrition\data\processed\hr_attrition_processed.csv', index=False)
print("Guardado Correctamente")

Guardado Correctamente